version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12.22.0
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/messageUtil-1.0.jar